### PR TITLE
Update 1.intro.md

### PR DESCRIPTION
**Pull request by domalex**
- fixed broken link

### CODE REVIEW

**Comment by Lorde627** [comment]
The link is not broken. In this wiki project, all local images use the "/img/xxx.jpg" path format.

**Comment by domalex** [comment]
The path to images is one up in folder hierarchy and then folder `/static` and then folder `/img`. Check your site on Github. Pictures are not shown: https://github.com/FydeOS/fydetabduo-wiki/blob/main/docs/1.intro.md

**Comment by Lorde627** [comment]
GitHub is only used to manage documents for the Wiki project; the final content is available at wiki.fydetabduo.com.

**Comment by domalex** [comment]
If you use the path I suggest the wiki is working on wiki.fydetabduo.com as well as on GitHub. I don't see a point why users who visit your GitHub shouldn't see pictures. Please reconsider amending the path that it works on both platforms. It doesn't cause any harm and helps contributers like me to help you creating and maintaining content more easily. We work on GitHub and not on the your website. Have a look at the wiki of Arch Linux or any other wiki maintained through GitHub. They all work on GitHub as well as on a website.

**Comment by Lorde627** [comment]
Currently, we cannot modify the paths due to constraints imposed by our documentation system, as detailed in https://docusaurus.io/docs/static-assets. You can clone the entire Fydetab Wiki project and use `yarn install && yarn start` to preview and edit the content locally in real time. Please note that the Markdown files in this GitHub repository are intended solely for documentation management, and the final rendered version can be viewed at wiki.fydetabduo.com.

**Comment by domalex** [comment]
Following the link https://docusaurus.io/docs/static-assets it says that

> Static assets are the non-code files that are **directly copied to the build output**. They include images, stylesheets, favicons, fonts, etc.
> By default, you are suggested to put these assets in the static folder. **Every file you put into that directory will be copied into the root of the generated build folder with the directory hierarchy preserved.** E.g. if you add a file named sun.jpg to the static folder, it will be copied to build/sun.jpg.
>
> This means that:
>
> for site baseUrl: '/', the image **/static/img/docusaurus.png will be served at /img/docusaurus.png.**
> for site baseUrl: '/subpath/', the image /static/img/docusaurus.png will be served at /subpath/img/docusaurus.png.

This means that even if you reference the links to `/static/img/<image-name>` it converts it on the website to the right place. I did it with my images and they all work well on GitHub and on your rendered website. Please check it. Just give it a try! You'll see.

I am just trying to help.

**Pull request closed without merging**
